name: attendance_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.1.1
  firebase_auth: 4.1.1
  cloud_firestore: 4.0.4
  firebase_storage: 11.0.4
  image_picker: 0.8.6
  convex_bottom_bar: 3.1.0+1
  intl: 0.17.0
  geolocator: 9.0.2
  geocoding: 2.0.4
  syncfusion_flutter_datepicker: 20.3.58
  loading_animation_widget: 1.2.0+3
  google_fonts: 3.0.1
  font_awesome_flutter: 10.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

