// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrW3CoiuHaeKsV3w8HxAesvccNZ6u1-Xc',
    appId: '1:639425989754:android:e8fab5de79ef7bc05cffc3',
    messagingSenderId: '639425989754',
    projectId: 'attendance-4d6c5',
    storageBucket: 'attendance-4d6c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZX4qyIkW11MXDOzbdJAF6qolk5a0-Ck4',
    appId: '1:639425989754:ios:8b632960832041885cffc3',
    messagingSenderId: '639425989754',
    projectId: 'attendance-4d6c5',
    storageBucket: 'attendance-4d6c5.appspot.com',
    androidClientId: '639425989754-raghq3ep6fi1ul5esd09b7buatrti93i.apps.googleusercontent.com',
    iosClientId: '639425989754-n164qf9gqsdr4alfim11abipra4d4kl8.apps.googleusercontent.com',
    iosBundleId: 'com.ranggsh.attendance',
  );
}
